version: "3.5"
services:
  awscli:
    image: lacti/docker-node-env:awscli
    build:
      context: awscli
  wine-awscli:
    image: lacti/docker-node-env:wine-awscli
    build:
      context: wine-awscli
